name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v5

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0

      - name: Check formatting
        run: pixi run format --check .

  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v5

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0

      - name: Check code
        run: pixi run lint

  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0

      - name: Setup envmodules
        run: |
          sudo apt-get update
          sudo apt-get install -y environment-modules

      - name: Run pytest
        shell: bash -el {0}
        run: |
          command -v module
          pixi run test -v

      - name: Run Coverage
        run: pixi run coverage-report
