on:
  push:
    branches:
      - main

name: release-please

env:
  PYTHON_VERSION: 3.11

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          release-type: python

  publish:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - uses: actions/checkout@v5

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0

      - name: Build source and wheel distribution + check build
        run: |
          pixi run check-build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
